print 1
raise Exception("The bug is on this line.")
